# lambda function: kotlin-ses-forward
# Receive S3 create event and get the mail object,
#  then forward to another email address.

service: kotlin-ses-forward

custom:
  region: us-west-2
  deploymentBucket: nakamata.tech-lambda
  eventBucket: nakamata.tech-ses

provider:
  name: aws
  runtime: java8
  deploymentBucket: ${self:custom.deploymentBucket}
  stage: dev
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::nakamata.tech-ses/*
    - Effect: "Allow"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

package:
  artifact: build/libs/kotlin-ses-forward-dev-all.jar

functions:
  kotlin-ses-forward:
    handler: tech.nakamata.Handler
    events:
      - s3:
          bucket: ${self:custom.eventBucket}
          event: s3:ObjectCreated:Put